export {default as Signin} from "./signin"
export {default as SignUp} from "./signup"
export {default as Student} from "./Student"
export {default as Teacher} from "./Teacher"
export {default as VerifyRegister} from "./verifyRegister"